"""Shared workspace paths, operation names, and execution defaults."""

from enum import StrEnum
from pathlib import Path


class RunKind(StrEnum):
    """Operation names used in prompts and workspace directories."""

    #: Initial kernel generation.
    INIT = "init"
    #: Removal of one optimization.
    DECOMPOSE = "decompose"
    #: One full kernel optimization round, with optional skill memory.
    APPLY = "apply"
    #: Review of an action's result.
    VERIFY = "verify"
    #: Skill memory generation from an expert kernel.
    INIT_MEMORY = "init-memory"
    #: Combined memory generation and optimization.
    WORKFLOW = "workflow"
    #: Iterative optimization with optional skill memory.
    OPTIMIZE = "optimize"
    #: Agent process execution.
    CODEX = "codex"
    #: Kernel correctness and timing evaluation.
    EVALUATE = "evaluate"


#: Parent directory for automatically allocated workspaces.
WORKSPACE_DIR = "experiment"
#: Serialized kernel artifact filename.
KERNEL_FILE = "kernel.json"
#: Source bundle configuration filename.
BUNDLE_CONFIG = "config.toml"
#: Digest prefix length used in generated module names.
MODULE_HASH_LENGTH = 20
#: Source directory within a configured bundle.
BUNDLE_SOLUTION = "solution"
#: Generated source bundle within an action workspace.
SUBMISSION_DIRECTORY = Path("submission")
#: Skill card filename within a skill directory.
SKILL_FILE = "SKILL.md"
#: Internal workspace state directory.
STATE_DIRECTORY = ".klineage"
#: Directory name for generated or mounted skill memory.
MEMORY_DIR = "memory"
#: Workspace directory discovered by the agent for skills.
SKILL_DIRECTORY = Path(".agents") / "skills"
#: Generated native memory skills relative to the agent workspace.
MEMORY_DIRECTORY = SKILL_DIRECTORY / MEMORY_DIR
#: Maximum name length in Codex SKILL.md frontmatter.
CODEX_SKILL_NAME_LIMIT = 64
#: Maximum description length in native skill frontmatter.
CODEX_SKILL_DESCRIPTION_LIMIT = 1024
#: Digest suffix distinguishing normalized or shortened skill IDs.
CODEX_SKILL_HASH_LENGTH = 12
#: Message schemas relative to the agent workspace.
MESSAGE_DIRECTORY = Path(STATE_DIRECTORY) / "message"
#: Build artifacts relative to the working directory.
BUILD_DIRECTORY = Path("build")
#: Evaluation logs relative to the working directory.
EVALUATIONS_DIRECTORY = Path("evaluations")
#: Workspace instruction files; a nonempty override takes precedence.
AGENT_FILES = ("AGENTS.md", "AGENTS.override.md")
#: Modules defining built-in agent functions beyond tools.profile.
AGENT_MODULES = (
    "klineage.backend",
    "klineage.artifact.kernel",
    "klineage.artifact.problem",
    "klineage.artifact.repository",
    "klineage.artifact.source",
    "klineage.harness.eval",
)
#: Workspace guidance placed above the generated agent-function catalog.
AGENTS_TEMPLATE = """You are a coding agent for writing optimized device kernels under `klineage` harness.
Use following helper functions provided by `klineage` harness to help you load/store artifacts, evaluate kernel performance
and profile bottlenecks. These helper functions gonna help you better organize your working directory and provide
accurate performance feedback towards faster kernels.

Hard Requirements:
- Save any intermediate device kernel artifact using `save_kernel` and load/build them next time with `load_kernel` and `build`.
- Evaluate and profile the performance of each version of the `Kernel` object generated by you only using `klineage.harness.eval.evaluate` and `klineage.tools.profile`.
Do not invent custom evaluation/profiling methods like writing your own profiling scripts, this is not admitted. These 2 functions are
the only performance gate that we trust.
"""


#: Start marker for generated agent function documentation.
FUNCTION_START = "<!-- klineage:agent-functions:start -->"
#: End marker for generated agent function documentation.
FUNCTION_END = "<!-- klineage:agent-functions:end -->"
#: Default retry limit after an action's first attempt.
MAX_RETRIES = 3
#: Default action timeout in seconds.
TIMEOUT = 3600
#: Absolute and relative tolerances for numerical output comparisons.
NUMERICAL_TOLERANCE = 1e-2
#: Default maximum number of Decompose invocations.
MAX_DECOMPOSE_STEPS = 15
#: Default maximum number of Apply optimization rounds.
MAX_APPLY_STEPS = 15
